import telebot
from telebot import types
from config import *
import sqlite3
from telebot.types import Message
from datetime import date

bot = telebot.TeleBot(token)

@bot.message_handler(commands=['start'])
def start(message: Message):
    markup = types.InlineKeyboardMarkup(row_width=2)
    btn3 = types.InlineKeyboardButton(text='Accounts', callback_data="Accs")
    markup.add(btn3)
    chat_id = message.chat.id
    it = date.today()
    its = str(it)
    itss = its[8:]
    con = sqlite3.connect('./Shop_DB.db')
    cur = con.cursor()
    cur.execute("SELECT Date FROM Shop_BD WHERE Admin=1")
    datex = cur.fetchone()
    con.commit()
    datexx = str(datex)
    datexxx = datexx[1:-2]
    cur.close()
    print(datexxx)
    con.close()
    if int(datexxx) == int(itss):
        bot.send_message(chat_id, 'Hello!', reply_markup=markup)
    else:
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("UPDATE Shop_BD SET Date=" + str(itss) + " WHERE admin=1")
        con.commit()
        cur.close()
        con.close()
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("UPDATE Shop_BD SET counter=0 ")
        con.commit()
        cur.close()
        con.close()
        bot.send_message(chat_id, 'Hello!', reply_markup=markup)


@bot.callback_query_handler(lambda message: True)
def call(message):
    chat_id = message.message.chat.id
    if message.data == 'Accs':
        data1 = int(chat_id)
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute('SELECT Types FROM Shop_BD WHERE Admin=1')
        dis1 = str(cur.fetchone())
        district1 = dis1[2:-2]
        cur.close()
        con.close()
        list = len(district1.split(','))
        print(list)
        # bot.send_message(chat_id, 'Hello')
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT UserClasses FROM Shop_BD WHERE Id_Users=" + str(data1) + "")
        fool = str(cur.fetchone())
        cur.close()
        con.close()
        if fool == 'None':
            bot.send_message(chat_id, 'bye')
            bot.delete_message(chat_id, message.message.message_id)
        else:
            if list == 1:
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type1 FROM Shop_BD LIMIT1')
                dis1 = str(cur.fetchone())
                cur.close()
                con.close()
                markup = types.InlineKeyboardMarkup(row_width=2)
                btn3 = types.InlineKeyboardButton(text=dis1, callback_data="11")
                markup.add(btn3)
                bot.send_message(chat_id, 'Hello', reply_markup=markup)
                bot.delete_message(chat_id, message.message.message_id)

            if list == 2:
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type1 FROM Shop_BD LIMIT 1')
                dis1 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type2 FROM Shop_BD LIMIT 1')
                dis2 = str(cur.fetchone())
                cur.close()
                con.close()
                markup = types.InlineKeyboardMarkup(row_width=2)
                btn1 = types.InlineKeyboardButton(text=dis1, callback_data="11")
                btn2 = types.InlineKeyboardButton(text=dis2, callback_data="12")
                markup.add(btn1, btn2)
                bot.send_message(chat_id, 'Hello', reply_markup=markup)
                bot.delete_message(chat_id, message.message.message_id)

            if list == 3:
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type1 FROM Shop_BD LIMIT 1')
                dis1 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type2 FROM Shop_BD LIMIT 1')
                dis2 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type3 FROM Shop_BD LIMIT 1')
                dis3 = str(cur.fetchone())
                cur.close()
                con.close()
                markup = types.InlineKeyboardMarkup(row_width=2)
                btn1 = types.InlineKeyboardButton(text=dis1, callback_data="11")
                btn2 = types.InlineKeyboardButton(text=dis2, callback_data="12")
                btn3 = types.InlineKeyboardButton(text=dis3, callback_data="13")
                markup.add(btn1, btn2, btn3)
                bot.send_message(chat_id, 'Hello', reply_markup=markup)
                bot.delete_message(chat_id, message.message.message_id)

            if list == 4:
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type1 FROM Shop_BD LIMIT 1')
                dis1 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type2 FROM Shop_BD LIMIT 1')
                dis2 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type3 FROM Shop_BD LIMIT 1')
                dis3 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type4 FROM Shop_BD LIMIT 1')
                dis4 = str(cur.fetchone())
                cur.close()
                con.close()
                markup = types.InlineKeyboardMarkup(row_width=2)
                btn1 = types.InlineKeyboardButton(text=dis1, callback_data="11")
                btn2 = types.InlineKeyboardButton(text=dis2, callback_data="12")
                btn3 = types.InlineKeyboardButton(text=dis3, callback_data="13")
                btn4 = types.InlineKeyboardButton(text=dis4, callback_data="14")
                markup.add(btn1, btn2, btn3, btn4)
                bot.send_message(chat_id, 'Hello', reply_markup=markup)
                bot.delete_message(chat_id, message.message.message_id)

            if list == 5:
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type1 FROM Shop_BD LIMIT 1')
                dis1 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type2 FROM Shop_BD LIMIT 1')
                dis2 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type3 FROM Shop_BD LIMIT 1')
                dis3 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type4 FROM Shop_BD LIMIT 1')
                dis4 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type5 FROM Shop_BD LIMIT 1')
                dis5 = str(cur.fetchone())
                cur.close()
                con.close()
                markup = types.InlineKeyboardMarkup(row_width=2)
                btn1 = types.InlineKeyboardButton(text=dis1, callback_data="11")
                btn2 = types.InlineKeyboardButton(text=dis2, callback_data="12")
                btn3 = types.InlineKeyboardButton(text=dis3, callback_data="13")
                btn4 = types.InlineKeyboardButton(text=dis4, callback_data="14")
                btn5 = types.InlineKeyboardButton(text=dis5, callback_data="15")
                markup.add(btn1, btn2, btn3, btn4, btn5)
                bot.send_message(chat_id, 'Hello', reply_markup=markup)
                bot.delete_message(chat_id, message.message.message_id)

            if list == 6:
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type1 FROM Shop_BD LIMIT 1')
                dis1 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type2 FROM Shop_BD LIMIT 1')
                dis2 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type3 FROM Shop_BD LIMIT 1')
                dis3 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type4 FROM Shop_BD LIMIT 1')
                dis4 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type5 FROM Shop_BD LIMIT 1')
                dis5 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type5 FROM Shop_BD LIMIT 1')
                dis6 = str(cur.fetchone())
                cur.close()
                con.close()
                markup = types.InlineKeyboardMarkup(row_width=2)
                btn1 = types.InlineKeyboardButton(text=dis1, callback_data="11")
                btn2 = types.InlineKeyboardButton(text=dis2, callback_data="12")
                btn3 = types.InlineKeyboardButton(text=dis3, callback_data="13")
                btn4 = types.InlineKeyboardButton(text=dis4, callback_data="14")
                btn5 = types.InlineKeyboardButton(text=dis5, callback_data="15")
                btn6 = types.InlineKeyboardButton(text=dis6, callback_data="16")
                markup.add(btn1, btn2, btn3, btn4, btn5, btn6)
                bot.send_message(chat_id, 'Hello', reply_markup=markup)
                bot.delete_message(chat_id, message.message.message_id)

            if list == 7:
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type1 FROM Shop_BD LIMIT 1')
                dis1 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type2 FROM Shop_BD LIMIT 1')
                dis2 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type3 FROM Shop_BD LIMIT 1')
                dis3 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type4 FROM Shop_BD LIMIT 1')
                dis4 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type5 FROM Shop_BD LIMIT 1')
                dis5 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type6 FROM Shop_BD LIMIT 1')
                dis6 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type7 FROM Shop_BD LIMIT 1')
                dis7 = str(cur.fetchone())
                cur.close()
                con.close()
                markup = types.InlineKeyboardMarkup(row_width=2)
                btn1 = types.InlineKeyboardButton(text=dis1, callback_data="11")
                btn2 = types.InlineKeyboardButton(text=dis2, callback_data="12")
                btn3 = types.InlineKeyboardButton(text=dis3, callback_data="13")
                btn4 = types.InlineKeyboardButton(text=dis4, callback_data="14")
                btn5 = types.InlineKeyboardButton(text=dis5, callback_data="15")
                btn6 = types.InlineKeyboardButton(text=dis6, callback_data="16")
                btn7 = types.InlineKeyboardButton(text=dis7, callback_data="17")
                markup.add(btn1, btn2, btn3, btn4, btn5, btn6, btn7)
                bot.send_message(chat_id, 'Hello', reply_markup=markup)
                bot.delete_message(chat_id, message.message.message_id)

            if list == 8:
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type1 FROM Shop_BD LIMIT 1')
                dis1 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type2 FROM Shop_BD LIMIT 1')
                dis2 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type3 FROM Shop_BD LIMIT 1')
                dis3 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type4 FROM Shop_BD LIMIT 1')
                dis4 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type5 FROM Shop_BD LIMIT 1')
                dis5 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type6 FROM Shop_BD LIMIT 1')
                dis6 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type7 FROM Shop_BD LIMIT 1')
                dis7 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type8 FROM Shop_BD LIMIT 1')
                dis8 = str(cur.fetchone())
                cur.close()
                con.close()
                markup = types.InlineKeyboardMarkup(row_width=2)
                btn1 = types.InlineKeyboardButton(text=dis1, callback_data="11")
                btn2 = types.InlineKeyboardButton(text=dis2, callback_data="12")
                btn3 = types.InlineKeyboardButton(text=dis3, callback_data="13")
                btn4 = types.InlineKeyboardButton(text=dis4, callback_data="14")
                btn5 = types.InlineKeyboardButton(text=dis5, callback_data="15")
                btn6 = types.InlineKeyboardButton(text=dis6, callback_data="16")
                btn7 = types.InlineKeyboardButton(text=dis7, callback_data="17")
                btn8 = types.InlineKeyboardButton(text=dis8, callback_data="18")
                markup.add(btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8)
                bot.send_message(chat_id, 'Hello', reply_markup=markup)
                bot.delete_message(chat_id, message.message.message_id)

            if list == 9:
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type1 FROM Shop_BD LIMIT 1')
                dis1 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type2 FROM Shop_BD LIMIT 1')
                dis2 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type3 FROM Shop_BD LIMIT 1')
                dis3 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type4 FROM Shop_BD LIMIT 1')
                dis4 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type5 FROM Shop_BD LIMIT 1')
                dis5 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type6 FROM Shop_BD LIMIT 1')
                dis6 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type7 FROM Shop_BD LIMIT 1')
                dis7 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type8 FROM Shop_BD LIMIT 1')
                dis8 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type9 FROM Shop_BD LIMIT 1')
                dis9 = str(cur.fetchone())
                cur.close()
                con.close()
                markup = types.InlineKeyboardMarkup(row_width=2)
                btn1 = types.InlineKeyboardButton(text=dis1, callback_data="11")
                btn2 = types.InlineKeyboardButton(text=dis2, callback_data="12")
                btn3 = types.InlineKeyboardButton(text=dis3, callback_data="13")
                btn4 = types.InlineKeyboardButton(text=dis4, callback_data="14")
                btn5 = types.InlineKeyboardButton(text=dis5, callback_data="15")
                btn6 = types.InlineKeyboardButton(text=dis6, callback_data="16")
                btn7 = types.InlineKeyboardButton(text=dis7, callback_data="17")
                btn8 = types.InlineKeyboardButton(text=dis8, callback_data="18")
                btn9 = types.InlineKeyboardButton(text=dis9, callback_data="19")
                markup.add(btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9)
                bot.send_message(chat_id, 'Hello', reply_markup=markup)
                bot.delete_message(chat_id, message.message.message_id)

            if list == 10:
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type1 FROM Shop_BD LIMIT 1')
                dis1 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type2 FROM Shop_BD LIMIT 1')
                dis2 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type3 FROM Shop_BD LIMIT 1')
                dis3 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type4 FROM Shop_BD LIMIT 1')
                dis4 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type5 FROM Shop_BD LIMIT 1')
                dis5 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type6 FROM Shop_BD LIMIT 1')
                dis6 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type7 FROM Shop_BD LIMIT 1')
                dis7 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type8 FROM Shop_BD LIMIT 1')
                dis8 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type9 FROM Shop_BD LIMIT 1')
                dis9 = str(cur.fetchone())
                cur.close()
                con.close()
                con = sqlite3.connect('./Shop_DB.db')
                cur = con.cursor()
                cur.execute('SELECT Type10 FROM Shop_BD LIMIT 1')
                dis10 = str(cur.fetchone())
                cur.close()
                con.close()
                markup = types.InlineKeyboardMarkup(row_width=2)
                btn1 = types.InlineKeyboardButton(text=dis1, callback_data="11")
                btn2 = types.InlineKeyboardButton(text=dis2, callback_data="12")
                btn3 = types.InlineKeyboardButton(text=dis3, callback_data="13")
                btn4 = types.InlineKeyboardButton(text=dis4, callback_data="14")
                btn5 = types.InlineKeyboardButton(text=dis5, callback_data="15")
                btn6 = types.InlineKeyboardButton(text=dis6, callback_data="16")
                btn7 = types.InlineKeyboardButton(text=dis7, callback_data="17")
                btn8 = types.InlineKeyboardButton(text=dis8, callback_data="18")
                btn9 = types.InlineKeyboardButton(text=dis9, callback_data="19")
                btn10 = types.InlineKeyboardButton(text=dis10, callback_data="20")
                markup.add(btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9, btn10)
                bot.send_message(chat_id, 'Hello', reply_markup=markup)
                bot.delete_message(chat_id, message.message.message_id)

    if message.data == 'Back':
        markup = types.InlineKeyboardMarkup(row_width=2)
        btn3 = types.InlineKeyboardButton(text='Accounts', callback_data="Accs")
        markup.add(btn3)
        bot.send_message(chat_id, 'Welcome back', reply_markup=markup)
        bot.delete_message(chat_id, message.message.message_id)

    if message.data == '11':
        data1 = int(chat_id)
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT UserClasses FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        x = str(cur.fetchone())
        y = x[1:-2]
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        z = str(cur.fetchone())
        x = z[1:-2]
        print(y)
        con.commit()
        cur.close()
        con.close()
        if y == '1' and x == '0':
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("UPDATE Shop_BD SET counter=1 WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type1 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ' , reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type1 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
            bot.delete_message(chat_id, message.message.message_id)
        if y == '1' and x == '1':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)

        if y == '10' and int(x) < 10:
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
            zx = cur.fetchone()
            zx1 = str(zx)
            zx2 = zx1[1:-2]
            zxc = int(zx2) + 1
            cur.execute("UPDATE Shop_BD SET counter=" + str(zxc) + " WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type1 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ', reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type1 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()

        if y == '10' and x == '10':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)

    if message.data == '12':
        data1 = int(chat_id)
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT UserClasses FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        x = str(cur.fetchone())
        y = x[1:-2]
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        z = str(cur.fetchone())
        x = z[1:-2]
        print(y)
        con.commit()
        cur.close()
        con.close()
        if y == '1' and x == '0':
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("UPDATE Shop_BD SET counter=1 WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type2 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ' , reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type2 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
        if y == '1' and x == '1':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)
        if y == '10' and int(x) < 10:
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
            zx = cur.fetchone()
            zx1 = str(zx)
            zx2 = zx1[1:-2]
            zxc = int(zx2) + 1
            cur.execute("UPDATE Shop_BD SET counter=" + str(zxc) + " WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type2 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ', reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type2 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()

        if y == '10' and x == '10':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)

    if message.data == '13':
        data1 = int(chat_id)
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT UserClasses FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        x = str(cur.fetchone())
        y = x[1:-2]
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        z = str(cur.fetchone())
        x = z[1:-2]
        print(y)
        con.commit()
        cur.close()
        con.close()
        if y == '1' and x == '0':
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("UPDATE Shop_BD SET counter=1 WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type3 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ' , reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type3 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
        if y == '1' and x == '1':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)
        if y == '10' and int(x) < 10:
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
            zx = cur.fetchone()
            zx1 = str(zx)
            zx2 = zx1[1:-2]
            zxc = int(zx2) + 1
            cur.execute("UPDATE Shop_BD SET counter=" + str(zxc) + " WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type3 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ', reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type3 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
        if y == '10' and x == '10':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)

    if message.data == '14':
        data1 = int(chat_id)
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT UserClasses FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        x = str(cur.fetchone())
        y = x[1:-2]
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        z = str(cur.fetchone())
        x = z[1:-2]
        print(y)
        con.commit()
        cur.close()
        con.close()
        if y == '1' and x == '0':
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("UPDATE Shop_BD SET counter=1 WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type4 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ' , reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type4 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
        if y == '1' and x == '1':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)
        if y == '10' and int(x) < 10:
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
            zx = cur.fetchone()
            zx1 = str(zx)
            zx2 = zx1[1:-2]
            zxc = int(zx2) + 1
            cur.execute("UPDATE Shop_BD SET counter=" + str(zxc) + " WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type4 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ', reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type4 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
        if y == '10' and x == '10':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)

    if message.data == '15':
        data1 = int(chat_id)
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT UserClasses FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        x = str(cur.fetchone())
        y = x[1:-2]
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        z = str(cur.fetchone())
        x = z[1:-2]
        print(y)
        con.commit()
        cur.close()
        con.close()
        if y == '1' and x == '0':
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("UPDATE Shop_BD SET counter=1 WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type5 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ' , reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type5 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
        if y == '1' and x == '1':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)
        if y == '10' and int(x) < 10:
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
            zx = cur.fetchone()
            zx1 = str(zx)
            zx2 = zx1[1:-2]
            zxc = int(zx2) + 1
            cur.execute("UPDATE Shop_BD SET counter=" + str(zxc) + " WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type5 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ', reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type5 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
        if y == '10' and x == '10':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)

    if message.data == '16':
        data1 = int(chat_id)
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT UserClasses FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        x = str(cur.fetchone())
        y = x[1:-2]
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        z = str(cur.fetchone())
        x = z[1:-2]
        print(y)
        con.commit()
        cur.close()
        con.close()
        if y == '1' and x == '0':
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("UPDATE Shop_BD SET counter=1 WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type6 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ' , reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type6 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
        if y == '1' and x == '1':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)
        if y == '10' and int(x) < 10:
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
            zx = cur.fetchone()
            zx1 = str(zx)
            zx2 = zx1[1:-2]
            zxc = int(zx2) + 1
            cur.execute("UPDATE Shop_BD SET counter=" + str(zxc) + " WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type6 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ', reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type6 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
        if y == '10' and x == '10':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)

    if message.data == '17':
        data1 = int(chat_id)
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT UserClasses FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        x = str(cur.fetchone())
        y = x[1:-2]
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        z = str(cur.fetchone())
        x = z[1:-2]
        print(y)
        con.commit()
        cur.close()
        con.close()
        if y == '1' and x == '0':
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("UPDATE Shop_BD SET counter=1 WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type7 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ' , reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type7 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
        if y == '1' and x == '1':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)
        if y == '10' and int(x) < 10:
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
            zx = cur.fetchone()
            zx1 = str(zx)
            zx2 = zx1[1:-2]
            zxc = int(zx2) + 1
            cur.execute("UPDATE Shop_BD SET counter=" + str(zxc) + " WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type7 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ', reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type7 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
        if y == '10' and x == '10':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)

    if message.data == '18':
        data1 = int(chat_id)
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT UserClasses FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        x = str(cur.fetchone())
        y = x[1:-2]
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        z = str(cur.fetchone())
        x = z[1:-2]
        print(y)
        con.commit()
        cur.close()
        con.close()
        if y == '1' and x == '0':
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("UPDATE Shop_BD SET counter=1 WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type8 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ' , reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type8 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
        if y == '1' and x == '1':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)
        if y == '10' and int(x) < 10:
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
            zx = cur.fetchone()
            zx1 = str(zx)
            zx2 = zx1[1:-2]
            zxc = int(zx2) + 1
            cur.execute("UPDATE Shop_BD SET counter=" + str(zxc) + " WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type8 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ', reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type8 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
        if y == '10' and x == '10':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)

    if message.data == '19':
        data1 = int(chat_id)
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT UserClasses FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        x = str(cur.fetchone())
        y = x[1:-2]
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        z = str(cur.fetchone())
        x = z[1:-2]
        print(y)
        con.commit()
        cur.close()
        con.close()
        if y == '1' and x == '0':
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("UPDATE Shop_BD SET counter=1 WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type9 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ' , reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type9 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
        if y == '1' and x == '1':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)
        if y == '10' and int(x) < 10:
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
            zx = cur.fetchone()
            zx1 = str(zx)
            zx2 = zx1[1:-2]
            zxc = int(zx2) + 1
            cur.execute("UPDATE Shop_BD SET counter=" + str(zxc) + " WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type9 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ', reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type9 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
        if y == '10' and x == '10':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)

    if message.data == '20':
        data1 = int(chat_id)
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT UserClasses FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        x = str(cur.fetchone())
        y = x[1:-2]
        con = sqlite3.connect('./Shop_DB.db')
        cur = con.cursor()
        cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
        z = str(cur.fetchone())
        x = z[1:-2]
        print(y)
        con.commit()
        cur.close()
        con.close()
        if y == '1' and x == '0':
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("UPDATE Shop_BD SET counter=1 WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type10 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ' , reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type10 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
        if y == '1' and x == '1':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)
        if y == '10' and int(x) < 10:
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("SELECT counter FROM Shop_BD WHERE Id_users=" + str(data1) + "")
            zx = cur.fetchone()
            zx1 = str(zx)
            zx2 = zx1[1:-2]
            zxc = int(zx2) + 1
            cur.execute("UPDATE Shop_BD SET counter=" + str(zxc) + " WHERE Id_users=" + str(data1) + "")
            con.commit()
            cur.close()
            con.close()
            chat_id = message.message.chat.id
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute('SELECT accounts FROM Type10 LIMIT 1')
            data1 = str(cur.fetchone())
            data2 = data1[2:-3]
            imgname = str(data2)
            con.commit()
            cur.close()
            con.close()
            bot.send_message(chat_id, 'account for you!:' + imgname + ' ', reply_markup=markup)
            bot.delete_message(message.message.chat.id, message.message.message_id)
            con = sqlite3.connect('./Shop_DB.db')
            cur = con.cursor()
            cur.execute("DELETE FROM Type10 WHERE accounts = '" + str(data2) + "' ")
            con.commit()
            cur.close()
        if y == '10' and x == '10':
            markup = types.InlineKeyboardMarkup(row_width=2)
            btn3 = types.InlineKeyboardButton(text='Back', callback_data="Back")
            markup.add(btn3)
            bot.send_message(chat_id, 'LIMIT is full', reply_markup=markup)
            bot.delete_message(chat_id, message.message.message_id)


bot.polling(none_stop=True)